version: "3"
services:
  node:
    image: config:latest
    user: node
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
